server {
    listen 80;
    listen [::]:80;
    server_name grafana.zhoushicheng.cn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name grafana.zhoushicheng.cn;

    ssl_certificate     /etc/cert/grafana.zhoushicheng.cn_bundle.crt;
    ssl_certificate_key /etc/cert/grafana.zhoushicheng.cn.key;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;

    proxy_read_timeout 1h;
    proxy_send_timeout 1h;
    send_timeout 1h;
    client_max_body_size 20m;

    location /analyze {
        proxy_pass http://127.0.0.1:8088;
    }

    location /healthz {
        proxy_pass http://127.0.0.1:8088;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
    }

    location /api/live/ {
        proxy_pass http://127.0.0.1:3000;
    }
}
